name: oguz_pay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  slang: ^4.2.1
  slang_flutter: ^4.2.0
  turkmen_localization_support: ^0.0.8

  # Media assets
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  lottie: ^3.1.3

  # Navigation
  auto_route: ^9.2.2

  # State management
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  
  # Utility
  talker_flutter: ^4.4.7
  qr_flutter: ^4.1.0
  collection: ^1.18.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.1.1
  
  # Data 
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_sembast_storage: ^0.2.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.3
  cached_network_image: ^3.3.1
  path_provider: ^2.1.5
  
  # Service locator
  get_it: ^8.0.2
  
  # UI
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.9
  water_drop_nav_bar: ^2.2.2
  introduction_screen: ^3.1.14
  animated_toggle_switch: ^0.8.3

dev_dependencies:
  flutter_lints: ^5.0.0

  # Testing
  flutter_test:
    sdk: flutter

  # Navigation
  auto_route_generator: ^9.0.0

  # State management
  mobx_codegen: ^2.6.2
  
  # App icon
  icons_launcher: ^3.0.0

  # Utility
  build_runner: ^2.4.13
  slang_build_runner: ^4.2.0
  flutter_gen_runner: ^5.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/tmp/
    - .env

flutter_gen:
  output: lib/generated/assets/
  line_length: 120

  colors:
    inputs:
      - assets/colors/colors.xml

  integrations:
    flutter_svg: true
    lottie: true
